name = "lightspeed-meta-capi"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Account
account_id = "2febeaec7b825dc19b659d7e783cf622"

# Worker Settings
workers_dev = true

# R2 Bindings (optioneel - voor logging)
# Uncomment als je R2 logging wilt gebruiken
# [[r2_buckets]]
# binding = "LOGS"
# bucket_name = "lightspeed-meta-logs"

# KV Namespaces (optioneel - voor caching/state)
# [[kv_namespaces]]
# binding = "CACHE"
# id = ""  # KV Namespace ID

# Environment Variables (non-sensitive only)
[vars]
NODE_ENV = "production"
DEBUG_MODE = "false"

# Cron Triggers - Poll Lightspeed orders every 5 minutes
[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

# Secrets (gebruik wrangler secret put voor deze)
# Deze zijn NIET in deze file, maar via CLI:
# wrangler secret put META_ACCESS_TOKEN
# wrangler secret put META_PIXEL_ID
# wrangler secret put LIGHTSPEED_API_KEY
# wrangler secret put LIGHTSPEED_API_SECRET
# wrangler secret put WEBHOOK_SECRET

# Triggers (optioneel - cron jobs)
# [triggers]
# crons = ["0 */4 * * *"]  # Elke 4 uur

# Build Configuration
[build]
command = "npm run build"

# Development Settings
[dev]
port = 8787
local_protocol = "http"
