name = "lightspeed-meta-capi"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Account
account_id = "2febeaec7b825dc19b659d7e783cf622"

# Worker Settings
workers_dev = true

# R2 Bindings (optioneel - voor logging)
# Uncomment als je R2 logging wilt gebruiken
# [[r2_buckets]]
# binding = "LOGS"
# bucket_name = "lightspeed-meta-logs"

# KV Namespaces
# 1. Order deduplication (prevent duplicate webhook processing)
[[kv_namespaces]]
binding = "ORDER_DEDUP"
id = "c261da492df0431d8ca4e74e71cb046e"
preview_id = "b7e3dee45ea84127b70a7d563425f041"

# 2. Pixel data storage (fbc, fbp from browser)
[[kv_namespaces]]
binding = "PIXEL_DATA_KV"
id = "12eed91ee98246308b01517ba9bd677f"
preview_id = "95434db769cb4823a955d9d48db9173d"

# Environment Variables (ALL credentials - using vars instead of secrets for reliability)
[vars]
NODE_ENV = "production"
DEBUG_MODE = "false"

# VikGinChoice Credentials
VIKGINCHOICE_LIGHTSPEED_API_KEY = "86d1160f58d16e09224b8f3351a96e90"
VIKGINCHOICE_LIGHTSPEED_API_SECRET = "764ecf6433ea31f0637affd77dcb03aa"
VIKGINCHOICE_LIGHTSPEED_SHOP_ID = "307649"
VIKGINCHOICE_META_ACCESS_TOKEN = "EAAX0dbtssvMBPuGHSIj2h8dM2kp8YAu1I9ObM7yi9ShVfkoPuDbmS4bLp9VZCeUAIdPOkgWovSwBTyguG2NGrfJpf77sFaM48dx05XjSfF4ZAproDgeM7p0XXabMEjMNFDeiMCPSTjVoTWtXUPZAvijB3fTRXotRTZBz1vJaFCIM9KhbHxltaa2eE21cZCwbEMwZDZD"
VIKGINCHOICE_META_PIXEL_ID = "2954295684696042"
VIKGINCHOICE_GA4_MEASUREMENT_ID = "G-P6152QHNZ6"
VIKGINCHOICE_GA4_API_SECRET = "eOcRAFvyR-mRORq7_MrhFw"

# Retoertje Credentials
RETOERTJE_LIGHTSPEED_API_KEY = "999dbf89325550b675d194b476692fe7"
RETOERTJE_LIGHTSPEED_API_SECRET = "de8afe8fd12e9b3cf1a06636274f286e"
RETOERTJE_LIGHTSPEED_SHOP_ID = "351609"
RETOERTJE_META_ACCESS_TOKEN = "EAAX0dbtssvMBPuGHSIj2h8dM2kp8YAu1I9ObM7yi9ShVfkoPuDbmS4bLp9VZCeUAIdPOkgWovSwBTyguG2NGrfJpf77sFaM48dx05XjSfF4ZAproDgeM7p0XXabMEjMNFDeiMCPSTjVoTWtXUPZAvijB3fTRXotRTZBz1vJaFCIM9KhbHxltaa2eE21cZCwbEMwZDZD"
RETOERTJE_META_PIXEL_ID = "1286370709492511"
RETOERTJE_GA4_MEASUREMENT_ID = "G-NBZL3D7WK8"
RETOERTJE_GA4_API_SECRET = "A0QeDogmTIOczyXBymszLw"

# Cron Triggers - Backup polling every hour (webhook is primary)
[triggers]
crons = ["0 * * * *"]  # Every hour at :00 (00:00, 01:00, 02:00, etc.)

# Secrets (gebruik wrangler secret put voor deze)
# Deze zijn NIET in deze file, maar via CLI:
# wrangler secret put META_ACCESS_TOKEN
# wrangler secret put META_PIXEL_ID
# wrangler secret put LIGHTSPEED_API_KEY
# wrangler secret put LIGHTSPEED_API_SECRET
# wrangler secret put WEBHOOK_SECRET

# Triggers (optioneel - cron jobs)
# [triggers]
# crons = ["0 */4 * * *"]  # Elke 4 uur

# Build Configuration
[build]
command = "npm run build"

# Development Settings
[dev]
port = 8787
local_protocol = "http"
